# Generated by Django 3.0.8 on 2020-10-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200818_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_street_address2',
            field=models.CharField(blank=True, default=' ', max_length=80, null=True),
        ),
    ]
