# Generated by Django 3.0.8 on 2020-08-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
