# Generated by Django 3.0.8 on 2020-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_pack_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='pack',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pack',
            name='publish_date',
            field=models.IntegerField(),
        ),
    ]
