# Generated by Django 3.0.8 on 2020-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_auto_20200804_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
