# Generated by Django 3.0.8 on 2020-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_auto_20200810_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='reduced_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
