# Generated by Django 3.0.8 on 2020-08-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0006_auto_20200810_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='image_url',
        ),
    ]
