# Generated by Django 3.0.8 on 2020-08-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0007_remove_pack_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='image',
            field=models.ImageField(default='../../media/noimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pack',
            name='publish_date',
            field=models.CharField(blank=True, default='2020/01/01', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='sku',
            field=models.CharField(max_length=254),
        ),
    ]
