# Generated by Django 3.0.8 on 2020-08-14 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0008_auto_20200814_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pack',
            name='sales',
            field=models.IntegerField(default='0', editable=False),
        ),
    ]
