# Generated by Django 3.0.8 on 2020-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0009_auto_20200814_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
