# Generated by Django 3.0.8 on 2020-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0012_auto_20200814_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='sample_track',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pack',
            name='image',
            field=models.ImageField(default='{{ MEDIA_URL }}noimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pack',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
