# Generated by Django 3.0.8 on 2020-08-18 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0016_auto_20200818_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
