# Generated by Django 3.0.8 on 2020-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0017_auto_20200818_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='download_file',
            field=models.FileField(default='.', upload_to=''),
        ),
    ]
