# Generated by Django 3.0.8 on 2020-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address1',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address2',
            field=models.CharField(default=' ', max_length=80),
        ),
    ]
